-intstyle "ise" -incremental -lib "secureip" -o "/home/xilinx/git/FPGA_NIGHT/final_project/master_tb_isim_beh.exe" -prj "/home/xilinx/git/FPGA_NIGHT/final_project/master_tb_beh.prj" "work.master_tb" 
